### ISSUE TITLE
Build a container to run

### ISSUE THREAD

**Issue by andypost** [cthos/d8-perf-casper#3]
Would be great to provide a Dockerfile to easy testing

**Comment by cthos** [comment]
Should be pretty simple. I'll see if I can get to that soon.

**Comment by cthos** [comment]
@andypost The initial idea is here: https://github.com/cthos/d8-perf-casper/blob/docker/Dockerfile

But, that'll just get you the prerequisites in a container, it won't expose the appropriate drush aliases you'd need to have running.

Not sure how best to handle that? Have a directory for placing appropriate drush aliases and then copy them as necessary in the container?

**Comment by cthos** [comment]
I think I'm just going to add a "drush" directory and expect you to put the relevant aliasfiles in there.

**Comment by cthos** [comment]
Lemme know if #4 works for you.
